version: '3'

services:

  # Not currently used, but could be helpful in the future
  geth:
    container_name: geth
    image: ethereum/client-go:stable
    ports:
        - "8545:8545"
    volumes:
        - "./.data/geth/dev-chain:/dev-chain"
    command: >
      --datadir dev-chain/
      --http
      --http.api eth,web3,personal,net
      --http.addr=0.0.0.0
      --http.vhosts='*'
      --dev
      --dev.period=14
