# syntax=docker/dockerfile:1
FROM denoland/deno:1.29.1
USER deno
WORKDIR /app
COPY deps.ts .
RUN deno cache deps.ts
COPY ./networks ./networks
COPY ./src ./src
COPY ./programs/aggregator.ts ./programs/aggregator.ts
RUN deno cache --unstable ./programs/aggregator.ts
ADD --chmod=664 --chown=deno https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem /aws/rds-ca.pem
CMD [ "run", "--unstable", "-A", "--cert", "/aws/rds-ca.pem", "./programs/aggregator.ts"]
