FROM node:18-alpine as BUILDER
WORKDIR /app
COPY ./aggregator-proxy/package.json ./aggregator-proxy/yarn.lock ./
RUN yarn
COPY ./aggregator-proxy ./
RUN yarn build

FROM node:18-alpine
WORKDIR /app
COPY --from=BUILDER /app/node_modules ./node_modules
COPY --from=BUILDER /app/package.json ./
COPY --from=BUILDER /app/dist ./
ENTRYPOINT [ "node", "startServer.js" ]
