name: aggregator
on:
  workflow_dispatch:
  push:
    paths:
      - aggregator/**
      - docker/Dockerfile.aggregator
    branches:
      - master
      - staging
      - qa
      - ci

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  aggregator_release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Login to Github Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: docker-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,enable=true,prefix=aggregator-${{ github.ref_name }},suffix=,format=short

      - name: Build and push
        id: docker-build-push
        uses: docker/build-push-action@v5
        with:
          file: docker/Dockerfile.aggregator
          push: true
          tags: ${{ steps.docker-meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: aggregator

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.K8S_DEPLOY_TOKEN }}
          repository: metisProtocol/k8s-apps
          event-type: apply_blswallet_aggregator_image
          client-payload: |
            {
              "ref_name": "${{ github.ref_name }}", 
              "image_tag": "${{ steps.docker-meta.outputs.tags }}"
            }
